### ISSUE TITLE
implemented user stories

### ISSUE THREAD

**Issue by melvincarvalho** [w3c-social/soc-ucr#7]
I was wondering, would it be possible to have some indication of which stories are actually implemented, as opposed tho which are proposed?

As for SoLiD both of the two user stories are implemented, live and have been demoed.

**Comment by akuckartz** [comment]
:+1:

**Comment by melvincarvalho** [comment]
From what I have gathered.

# Total proposed user stories

10

# Total implemented user stories

3-5

# Proposed user stories written up:

Activity pump: 4
Indieweb : 4
SoLiD: 2

# Implemented User Stories

SoLiD: 2
Indieweb: 1\* (see below)
Activity pump: 0

# Notes
- User posts a note is implemented
- SWAT0 partially implemented
- User posts a file partially implemented if that file is inlined, 
- Responses are partially implemented, indieweb does not have an inbox some argue webmention endpoint is an 'inbox' some argue that it isnt

It has been difficult to clarify the above, so any further guidance is welcome. 

SoLiD has a working implementation of direct messaging.  Hopefully this can be the 3rd implemented user story written up.

**Comment by melvincarvalho** [comment]
thanks to @aaronpk for adding implementations badges, I think this is a big improvement

I suggest we close this issue, unless there's an objection ...

**Comment by aaronpk** [comment]
Thanks! The badges should help with this.
